model:
  backbone: resnet50
  num_classes: 2
  pretrained: true
  learning_rate:  0.0050 
  epochs: 10
  batch_size: 8
  optimizer: adam
  image_sample_size: 10
  trainable_backbone_layers: 3

dataset:
  image_dir: datasets/images
  annotation_dir: datasets/annotations
  train_split: 0.8
  val_split: 0.2

notebooks:
  visualization: models/training_log.json

logs:
  log_dir: models/training_log.txt
  log_interval: 10

evaluation:
  iou_threshold: 0.5
