model:
  backbone: resnet50
  num_classes: 2
  pretrained: true
  learning_rate:  0.0050 
  epochs: 10
  batch_size: 8
  optimizer: adam
  image_sample_size: 10000
  trainable_backbone_layers: 1

dataset:
  image_dir: datasets/images
  annotation_dir: datasets/annotations
  train_split: 0.8
  val_split: 0.2

notebooks:
  visualization: logs/training_log.json

logs:
  log_dir: logs/training_log.txt
  log_interval: 10

evaluation:
  iou_threshold: 0.5
